-- MySQL Script generated by MySQL Workbench
-- Thu Dec 11 09:20:16 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cms` DEFAULT CHARACTER SET utf8 ;
USE `cms` ;

-- -----------------------------------------------------
-- Table `cms`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms`.`user` (
  `id_u` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(20) NULL COMMENT 'Имя пользователя',
  `last_name` VARCHAR(30) NULL COMMENT 'Фамилия пользователя',
  `email` VARCHAR(100) NOT NULL COMMENT 'Электронная почта',
  `phone_number` VARCHAR(15) NOT NULL COMMENT 'Номер телефона',
  `password` VARCHAR(30) NOT NULL COMMENT 'Пароль',
  `registration_date` DATE NULL COMMENT 'Дата регистрации',
  `last_visit` DATE NULL COMMENT 'дата последнего посещения',
  `username` VARCHAR(60) NOT NULL COMMENT 'Ник пользователя',
  `is_active` TINYINT(1) NOT NULL COMMENT 'Активность пользователя',
  PRIMARY KEY (`id_u`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cms`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms`.`role` (
  `id_r` INT NOT NULL AUTO_INCREMENT,
  `name_role` VARCHAR(50) NOT NULL COMMENT 'Название роли',
  PRIMARY KEY (`id_r`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cms`.`role_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms`.`role_has_user` (
  `role_id_r` INT NOT NULL,
  `user_id_u` INT NOT NULL,
  PRIMARY KEY (`role_id_r`, `user_id_u`),
  INDEX `fk_role_has_user_user1_idx` (`user_id_u` ASC) VISIBLE,
  INDEX `fk_role_has_user_role_idx` (`role_id_r` ASC) VISIBLE,
  CONSTRAINT `fk_role_has_user_role`
    FOREIGN KEY (`role_id_r`)
    REFERENCES `cms`.`role` (`id_r`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_has_user_user1`
    FOREIGN KEY (`user_id_u`)
    REFERENCES `cms`.`user` (`id_u`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cms`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms`.`permission` (
  `id_p` INT NOT NULL AUTO_INCREMENT,
  `name_p` VARCHAR(45) NOT NULL COMMENT 'Название права',
  `description` VARCHAR(100) NOT NULL COMMENT 'описание права',
  `action` VARCHAR(20) NOT NULL COMMENT 'Тип права',
  `code` VARCHAR(20) NOT NULL COMMENT 'Машинный код',
  PRIMARY KEY (`id_p`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cms`.`role_has_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms`.`role_has_permission` (
  `role_id_r` INT NOT NULL,
  `permission_id_p` INT NOT NULL,
  PRIMARY KEY (`role_id_r`, `permission_id_p`),
  INDEX `fk_role_has_permission_permission1_idx` (`permission_id_p` ASC) VISIBLE,
  INDEX `fk_role_has_permission_role1_idx` (`role_id_r` ASC) VISIBLE,
  CONSTRAINT `fk_role_has_permission_role1`
    FOREIGN KEY (`role_id_r`)
    REFERENCES `cms`.`role` (`id_r`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_has_permission_permission1`
    FOREIGN KEY (`permission_id_p`)
    REFERENCES `cms`.`permission` (`id_p`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cms`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms`.`categories` (
  `id_c` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL COMMENT 'Название категории',
  `slug` VARCHAR(200) NOT NULL COMMENT 'URL-путь категории',
  `parent_id` INT NULL COMMENT 'Родительская категория (NULL = корневая)',
  `sort_order` INT NOT NULL DEFAULT 0 COMMENT 'Порядок отображения внутри родителя',
  `is_activec` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Видимость категории',
  `created` DATE NULL COMMENT 'Дата создания',
  `updated` DATE NULL COMMENT 'Последнее изменение',
  `categories_id_c` INT NULL,
  PRIMARY KEY (`id_c`),
  INDEX `fk_categories_categories1_idx` (`categories_id_c` ASC) VISIBLE,
  CONSTRAINT `fk_categories_categories1`
    FOREIGN KEY (`categories_id_c`)
    REFERENCES `cms`.`categories` (`id_c`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cms`.`content_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms`.`content_type` (
  `id_ct` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL COMMENT 'Название типа ',
  `label` VARCHAR(150) NOT NULL COMMENT 'Код',
  `created_at` DATE NOT NULL COMMENT 'Дата создания',
  PRIMARY KEY (`id_ct`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cms`.`content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms`.`content` (
  `id_cont` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `slug` VARCHAR(200) NOT NULL,
  `content_body` VARCHAR(200) NULL,
  `status` ENUM('draft', 'published', 'archived') NOT NULL,
  `excerpt` VARCHAR(200) NULL,
  `published_at` DATE NULL,
  `created_at` DATE NOT NULL,
  `updated_at` DATE NULL,
  `categories_id_c` INT NOT NULL,
  `user_id_u` INT NOT NULL,
  `content_type_id_ct` INT NOT NULL,
  PRIMARY KEY (`id_cont`),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC) VISIBLE,
  INDEX `fk_content_categories1_idx` (`categories_id_c` ASC) VISIBLE,
  INDEX `fk_content_user1_idx` (`user_id_u` ASC) VISIBLE,
  INDEX `fk_content_content_type1_idx` (`content_type_id_ct` ASC) VISIBLE,
  CONSTRAINT `fk_content_categories1`
    FOREIGN KEY (`categories_id_c`)
    REFERENCES `cms`.`categories` (`id_c`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_content_user1`
    FOREIGN KEY (`user_id_u`)
    REFERENCES `cms`.`user` (`id_u`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_content_content_type1`
    FOREIGN KEY (`content_type_id_ct`)
    REFERENCES `cms`.`content_type` (`id_ct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cms`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms`.`tags` (
  `id_t` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL COMMENT 'Название тега',
  `slug` VARCHAR(150) NOT NULL COMMENT 'Уникальный URL-тег',
  `created_at` DATE NOT NULL COMMENT 'Дата создания',
  PRIMARY KEY (`id_t`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cms`.`cont_versions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms`.`cont_versions` (
  `id_cv` INT NOT NULL AUTO_INCREMENT,
  `numbervers` INT NOT NULL COMMENT 'номер версии',
  `title` VARCHAR(200) NOT NULL COMMENT 'версия заголовка',
  `excerpt` VARCHAR(200) NULL COMMENT 'версия краткого описания',
  `content_body` VARCHAR(200) NULL COMMENT 'текст версии',
  `created_at` DATE NULL COMMENT 'дата создания',
  `created_by` INT NOT NULL COMMENT 'кем создана',
  `content_id_cont` INT NOT NULL,
  PRIMARY KEY (`id_cv`, `content_id_cont`),
  INDEX `fk_cont_versions_content1_idx` (`content_id_cont` ASC) VISIBLE,
  CONSTRAINT `fk_cont_versions_content1`
    FOREIGN KEY (`content_id_cont`)
    REFERENCES `cms`.`content` (`id_cont`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cms`.`content_has_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms`.`content_has_tags` (
  `content_id_cont` INT NOT NULL,
  `tags_id_t` INT NOT NULL,
  PRIMARY KEY (`content_id_cont`, `tags_id_t`),
  INDEX `fk_content_has_tags_tags1_idx` (`tags_id_t` ASC) VISIBLE,
  INDEX `fk_content_has_tags_content1_idx` (`content_id_cont` ASC) VISIBLE,
  CONSTRAINT `fk_content_has_tags_content1`
    FOREIGN KEY (`content_id_cont`)
    REFERENCES `cms`.`content` (`id_cont`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_content_has_tags_tags1`
    FOREIGN KEY (`tags_id_t`)
    REFERENCES `cms`.`tags` (`id_t`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
